version: '3.3'
services:
  threejs_game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: threejs_game
    stdin_open: true
    tty: true
    ports:
      - "3010:3010"
    restart: always
